# Generated by Django 5.2.4 on 2025-07-19 12:49

import cloudinary.models
import product.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                validators=[product.validators.validate_file_size],
                verbose_name="image",
            ),
        ),
    ]
