# Generated by Django 5.2.4 on 2025-07-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_review_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="description",
            new_name="comment",
        ),
    ]
