# Generated by Django 5.2.4 on 2025-07-19 12:20

import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/images",
                validators=[product.validators.validate_file_size],
            ),
        ),
    ]
