# Generated by Django 5.2.4 on 2025-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Paid", "Not Paid"),
                    ("Ready to Ship", "Ready to Ship"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Not Paid",
                max_length=15,
            ),
        ),
    ]
